apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
        version: v1
    spec:
      containers:
      - name: rev
        image: skyglass/review-service:1.0.0
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker,prod"
        - name: SPRING_CONFIG_LOCATION
          value: file:/config-repo/application.yml,file:/config-repo/review.yml
        envFrom:
        - secretRef:
            name: rabbitmq-credentials
        - secretRef:
            name: mysql-credentials
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "400Mi"
        volumeMounts:
        - name: config-repo-volume
          mountPath: /config-repo
      volumes:
      - name: config-repo-volume
        configMap:
          name: config-repo-review

---
apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  selector:
    app: review
  ports:
    - name: http
      port: 80
      targetPort: 80