server.port: 7001
server.error.include-message: always

spring.application.name: product

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://istio.skycomposer.net/auth/realms/demo
          jwk-set-uri: https://istio.skycomposer.net/auth/realms/demo/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            client-id: demoapp
            client-secret: demoapp
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirectUri: 'https://istio.skycomposer.net/product-composite/swagger-ui/index.html'
            redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            authorization-uri: https://istio.skycomposer.net/auth/realms/demo/protocol/openid-connect/auth
            token-uri: https://istio.skycomposer.net/auth/realms/demo/protocol/openid-connect/token
            user-info-uri: https://istio.skycomposer.net/auth/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: https://istio.skycomposer.net/auth/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username

opentracing:
  jaeger:
    log-spans: true
    enable-b3-propagation: true
    enabled: true
    http-sender:
      url: http://jaeger-collector.istio-system:14268/api/traces

app.product-service.timeoutSec: 2


---
spring.config.activate.on-profile: docker

server.port: 80

spring.data.mongodb.host: mongodb

---
spring.config.activate.on-profile: streaming_partitioned
spring.cloud.stream.bindings.input.consumer:
  partitioned: true
  instanceCount: 2

---
spring.config.activate.on-profile: streaming_instance_0
spring.cloud.stream.bindings.input.consumer.instanceIndex: 0

---
spring.config.activate.on-profile: streaming_instance_1
spring.cloud.stream.bindings.input.consumer.instanceIndex: 1

---
spring.config.activate.on-profile: prod

spring.data.mongodb.host: mongodb

logging:
  level:
    root: INFO
    skyglass.composer: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG    
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: WARN
